### ISSUE TITLE
"OS Error" when trying to generate slaves.json

### ISSUE THREAD

**Issue by hdelatorre** [theQRL/QRL#1024]
ubuntu@ip:~/.qrl$ qrl -r --host 104.251.219.215 slave_tx_generate
Src []: 0
Addr from (Leave blank in case same as source) []:
Number of slaves [0]: 4
Access type [0]: 1
Fee [0.0]: 0
Generating Slave #1
Successfully Generated Slave 1/4
Generating Slave #2
Successfully Generated Slave 2/4
Generating Slave #3
Successfully Generated Slave 3/4
Generating Slave #4
Successfully Generated Slave 4/4
**OS Error**
ubuntu@ip:~/.qrl$ ls -alh
total 12K
drwxrwxr-x 2 ubuntu ubuntu 4.0K Mar  8 23:18 .
drwxr-xr-x 6 ubuntu ubuntu 4.0K Mar  8 23:18 ..
-rw-rw-r-- 1 ubuntu ubuntu  298 Mar  8 23:16 wallet.qrl

**Comment by ghost** [comment]
It appears as though the wallet already existed and an attempt to overwrite the index wallet 0 happened.

I say because an O/S error is IO error, so it could not write to the directory or overwrite the already-existing file data. Wallet would not exist in the case of IO error (when I got this error no wallet was outputted into home ~)

**Comment by jleni** [comment]
slaves are not necessary anymore. closing
