### ISSUE TITLE
Fails to compile on Mac OS 10.12.6

### ISSUE THREAD

**Issue by ubidefeo** [theQRL/QRL#468]
I have Python 3.6.3 via PyEnv and tried the install process with `sudo pip3 install -r requirements.txt`.
The process fails when `PYTHON_LIBRARIES` and `PYTHON_INCLUDE_DIRS`are not found, and think they should be added to` CMakeLists.txt` of qrllib, but this is installed via `requirements.txt`.

Is there a way I can specify them in the QRL setup?
Should I attempt to just download/install qrllib separately rather than via requirements.txt?

thank you
u.

**Comment by jleni** [comment]
Hi @ubidefeo 
qrllib is using `find_package(PythonLibs 3.4 REQUIRED)` [(cmake's FindPythonLibs)](https://cmake.org/cmake/help/v3.0/module/FindPythonLibs.html) to detect python development libraries. These two should have been set. Are you sure you have the python development headers installed?

We suggest using brew because it does not only install python but also the contents of python-devel (header files, etc.).

You can always follow the instructions in qrllib to install it independently.

**Comment by ubidefeo** [comment]
thank you @jleni 
I'll try installing python3 with homebrew, although I kinda like the PyEnv way.

Keep you posted :)

**Comment by jleni** [comment]
As far as I understand, you can use both simultaneously. I cannot be sure because I don't use PyEnv, however, I use python with both brew and conda without problems.

**Comment by ubidefeo** [comment]
@jleni 
wow!

- disabled `pyenv init` from my `env.sh`
- `brew install python3`
- `exec $SHELL`
- `sudo pip3 install -r requirements.txt`

BOOM!
```
Successfully installed Automat-0.6.0 PyYAML-3.12 Twisted-17.9.0...
```

thank you so much for the heads-up. I would have struggled for quite a while :D

**Comment by jleni** [comment]
no problem :+1:
