### ISSUE TITLE
Testnet or not testnet?

### ISSUE THREAD

**Issue by jupiter126** [theQRL/QRL#86]
So I carefully read and applied the pdf, and got the node runnig in gentoo.
What bothers me, is that at the end of the pdf it is written to contact to get fake money.  Is this wallet still a testnet wallet, or can I safely transfer some "real" quantas out of an exchange, and into that wallet?

**Comment by surg0r** [comment]
The value is currently floating on ERC20 tokens atop the eth mainnet. We
will migrate tokens to our QRL mainnet upon launch.

Testnet is for testing purposes and never carries monetary value.

For testnet coins once public testnet is back up head to slack.theqrl.org

Kindest regards,

Peter

**Comment by jupiter126** [comment]
So this would confirm that I should not transfer my QRL coins from bittrex to the address I see in the wallet from this git

**Comment by surg0r** [comment]
Correct!

**Comment by surg0r** [comment]
Correct!

On 14 Jun 2017 2:38 p.m., "jupiter126" <notifications@github.com> wrote:

So this would confirm that I should not transfer my QRL coins from bittrex
to the address I see in the wallet from this git

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/theQRL/QRL/issues/86#issuecomment-308433652>, or mute
the thread

**Comment by jupiter126** [comment]
Thanks a lot for rapid and precise answer ;)
