### ISSUE TITLE
Can't install on ProxMox Virtual Machine (missing AES-NI support)

### ISSUE THREAD

**Issue by Yzord** [theQRL/QRL#895]
https://pastebin.com/cxXXS6LD

Had this issue on Ubuntu 16.04 and on Debian 9. Looks like something is not right with building?

**Comment by jleni** [comment]
What is the CPU that you are using? 

We are using an instruction set: AES-NI (https://en.wikipedia.org/wiki/AES_instruction_set) that is not supported in old CPUs

While we could work on supporting very old CPUs, they would not be actually effective due to the higher requirements of the cryptonight algorithm.

I agree that it may make sense to automatically detect CPU capabilities and show an appropriate error message.

**Comment by Yzord** [comment]
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            15
Model:                 6
Model name:            Common KVM processor
Stepping:              1
CPU MHz:               2933.436
BogoMIPS:              5866.87
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              4096K
NUMA node0 CPU(s):     0
NUMA node1 CPU(s):     1
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx lm constant_tsc nopl xtopology eagerfpu pni cx16 x2apic hypervisor lahf_lm

It's the Xeon X5570

**Comment by jleni** [comment]
ok, you seem to be running a virtual machine. 

Could you tell me what are you using? Vmware, Virtualbox, etc? It would be good to document the environment so we see if there is any chance of supporting that in the near future. At least with the miner disabled.

**Comment by Yzord** [comment]
I run Proxmox on dedicated servers

**Comment by jleni** [comment]
I have updated the title to be more specific about the problem
