### ISSUE TITLE
miner skipping current blocks as beyond lead limit

### ISSUE THREAD

**Issue by baudje** [theQRL/QRL#940]
[qrl.log](https://github.com/theQRL/QRL/files/1743918/qrl.log) 

NB timezone = ETC, OS = OS X
QRL miner seems to have been mining an alternative chain. Found 
many solutions for blocks that the main chain had already mined earlier. 
Miner skips recent blocks received from other nodes as beyond lead limit. Full log attached

**Comment by jleni** [comment]
@cyyber I think you might want to have a look at this.

**Comment by baudje** [comment]
NB versions of relevant other packages:
```
Requirement already up-to-date: pyqryptonight<0.7.0,>=0.6.0 in /usr/local/lib/python3.6/site-packages (from qrl)
Requirement already up-to-date: pyqrllib<0.6.0,>=0.5.1 in /usr/local/lib/python3.6/site-packages (from qrl)
```

**Comment by jleni** [comment]
Normally this message means that the node has received a block with an index that is too high for the current blockchain. It could be a problem or not. 
We need to analyse the log files.

**Comment by baudje** [comment]
the problem from a mining perspective is that the miner seems to be unable to catch up with the main chain (if the chain in blockexplorer actually is the main chain).

**Comment by jleni** [comment]
Yes, I understood that and it is why I am giving priority to this issue. We will write back soon.
Thanks a lot for your support / feedback

**Comment by cyyber** [comment]
@baudje This is an expected behavior.
From the log its clear, your node was downloading block #19592 
and at that same time, all the synced nodes, were mining around block number #23223. We have a filter, that a node will not accept any future block which is beyond the range of current chain height + 125
so your node height was 19591+125 = 19716
So your node will reject all blocks above the block number 19716

Moreover, it doesn't mean as it will keep downloading blocks, it will not sync above that. Looking to the log, your node successfully synced.
